### ISSUE TITLE
Wedding DJ

### ISSUE THREAD

**Issue by amccaugh** [amccaugh/experiments#3]
Need to get info, make sure we have songs, etc
 - [ ] Here's a thing
 - Testing another

https://github.com/amccaugh/experiments/wiki/Awesome-wedding-page

Can I refer to a file now?  [This file](https://github.com/amccaugh/experiments/blob/ce77f128a7b38f11fb3c7b2815ee6f47bbba2673/Rehearsal%20Dinner%20Contract%20SKMBT_C45115050513010.pdf)

**Comment by amccaugh** [comment]
# ######################################
# Initial selection (April 23, 2015)
# ######################################
    BRUSCHETTA DISPLAY  $15.50 pp 
    GRILLED VEGETABLE DISPLAY  $13.50 pp 
    *ITALIAN PASTA BAR  $25 pp 
    *ROAST TURKEY  $275 each 
     *Roasted Top Round of Beef  ($375 each / 50 guests)
        * Add $125 for someone to man the station
## Mom's comments:
    Wants fresh fruit

**Comment by amccaugh** [comment]
# ######################################
# Revised selection 2A (Sept 3, 2015)
# ######################################
    BRUSCHETTA DISPLAY  $15.50 pp 
    GRILLED VEGETABLE DISPLAY  $13.50 pp 
    *ITALIAN PASTA BAR  $25 pp 
    *ROAST TURKEY  $275 each 
    Roasted leg of lamb ($400 each / 30 guests)
        or Roast pork caribbean steamship ($500 each / 50 guests)

**Comment by amccaugh** [comment]
I think this has a lot to do with #2

**Comment by vanessafrontiero** [comment]
@amccaugh I love that you're using Github for this.

**Comment by clj02fsu** [comment]
Hahahahhahahah!

**Comment by amccaugh** [comment]
@vanessafrontiero You better watch out or I'm gonna make you the assignee to some of our issues!

**Comment by vanessafrontiero** [comment]
always hit up a handle @amccaugh, this way someone can get an alert. Also, think about it visually maybe...  

You could make each larger task a repo. i.e.**/wedding logistics**

then umbrella by issue in that repo;
- [ ]  DJ options
- [ ]  menu options

then additional repos; 

### wedding rehearsal 
- [ ] food
- [ ] guest list

**Comment by vanessafrontiero** [comment]
September | October | November
--- | --- | ---
Wedding Prep | Married | Vanessa Bday
